// Firestore collection names (mirrors the former Prisma models).
export const COL = {
  roles: 'roles',
  users: 'users',
  signupRequests: 'signupRequests',
  projects: 'projects',
  milestones: 'milestones',
  ganttItems: 'ganttItems',
  tasks: 'tasks',
  taskLogs: 'taskLogs',
  comments: 'comments',
  clients: 'clients',
  leads: 'leads',
  invoices: 'invoices',
  documents: 'documents',
  tickets: 'tickets',
  leaves: 'leaves',
  salaryRecords: 'salaryRecords',
  salaryChangeLogs: 'salaryChangeLogs',
  payrollEntries: 'payrollEntries',
  attendanceSessions: 'attendanceSessions',
  bugs: 'bugs',
  notifications: 'notifications',
  auditLogs: 'auditLogs',
} as const;
